name: 'Supported PHP Versions'
description: 'Outputs supported PHP versions from data synced with php.net (no runtime fetch)'
branding:
  icon: 'list'
  color: 'green'
inputs:
  upcomingReleases:
    description: 'Include upcoming new major or minor releases'
    required: false
outputs:
  versions:
    description: 'JSON array with the supported versions'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/wyrihaximus/github-action-supported-php-versions:master'
