name: Continuous Integration
env:
  DOCKER_BUILDKIT: 1
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
  packages: write
jobs:
  generate-ref:
    name: Generate Ref
    runs-on: ubuntu-latest
    outputs:
      REF: ${{ steps.generate-ref.outputs.ref }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - id: generate-ref
        name: Generate Ref
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] ; then
            ref=$(php -r "echo str_replace('/', '-SLASH-', '${{ github.event.pull_request.head.ref }}');")
            echo "$ref"
            echo "ref=$ref" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "${GITHUB_REF##*/}"
          echo "ref=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Lint Dockerfile
        uses: docker://hadolint/hadolint:latest-debian
        with:
          entrypoint: hadolint
          args: Dockerfile
  build-docker-image:
    name: Build Docker image
    needs:
      - generate-ref
      - lint-dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io \
            --username "${GITHUB_ACTOR}" \
            --password-stdin
      - name: Set up QEMU
        uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
        with:
          install: true
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - run: docker version
      - run: docker images
      - run: docker build --platform=linux/arm64,linux/amd64 --output=type=registry --no-cache -t "$(echo "ghcr.io/${GITHUB_REPOSITORY}:${{ needs.generate-ref.outputs.ref }}" | tr '[:upper:]' '[:lower:]')" . -f Dockerfile
      - run: |
          printf "FROM %s" "$(echo "ghcr.io/${GITHUB_REPOSITORY}:${{ needs.generate-ref.outputs.ref }}" | tr '[:upper:]' '[:lower:]')" > Dockerfile.tag
          docker build --platform=linux/arm64,linux/amd64 --output=type=registry --no-cache -f Dockerfile.tag -t "$(echo "ghcr.io/${GITHUB_REPOSITORY}:sha-${GITHUB_SHA}" | tr '[:upper:]' '[:lower:]')" .
      - run: docker images
  fetch-versions:
    name: Fetch Versions
    needs:
      - build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          docker login ghcr.io \
            --username "${GITHUB_ACTOR}" \
            --password-stdin
      - run: sed -i "s/:master/:sha-${GITHUB_SHA}/g" action.yml
      - run: cat action.yml
      - name: Fetch Versions
        uses: ./
        id: versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show Versions
        run: echo "${VERSIONS}"
        env:
          VERSIONS: ${{ steps.versions.outputs.versions }}
      - name: Assert Versions output is non-empty
        uses: nick-fields/assert-action@0efd6166067d9c59d89c710fab4f79fb066f8985 # v4.0.1
        with:
          expected: "["
          actual: ${{ steps.versions.outputs.versions }}
          comparison: startsWith
      - name: Fetch Versions including upcoming releases
        uses: ./
        id: versionsincludingupcomingreleases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upcomingReleases: true
      - name: Show Versions including upcoming releases
        run: echo "${VERSIONS}"
        env:
          VERSIONS: ${{ steps.versionsincludingupcomingreleases.outputs.versions }}
      - name: Assert Versions including upcoming releases output is non-empty
        uses: nick-fields/assert-action@0efd6166067d9c59d89c710fab4f79fb066f8985 # v4.0.1
        with:
          expected: "["
          actual: ${{ steps.versionsincludingupcomingreleases.outputs.versions }}
          comparison: startsWith
